### ISSUE TITLE
Following install & login - unknown attribute 'action' for Audited::Audit.

### ISSUE THREAD

**Issue by chrislockwood** [RealEnder/redmine_auditlog#3]
**Environment**

Redmine version           4.1.1.stable
Ruby version                 2.6.6-p146 (2020-03-31) [x64-mingw32]
Rails version                  5.2.4.2
Environment                  production
Database adapter          SQLServer

**Log**
>Successful authentication for 'chris_lockwood' from 127.0.0.1 at 2021-01-16 19:33:05 UTC
Completed 500 Internal Server Error in 470ms (ActiveRecord: 209.6ms)
  
>ActiveModel::UnknownAttributeError (unknown attribute 'action' for Audited::Audit.):
  
>app/models/user.rb:435:in `generate_session_token'
app/controllers/application_controller.rb:88:in `start_user_session'
app/controllers/application_controller.rb:168:in `logged_user='
app/controllers/account_controller.rb:281:in `successful_authentication'
app/controllers/account_controller.rb:227:in `password_authentication'
app/controllers/account_controller.rb:213:in `authenticate_user'
app/controllers/account_controller.rb:40:in `login'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

**Comment by RealEnder** [comment]
Hi, if you remove the auditlog plugin do you still get this issue?

**Comment by chrislockwood** [comment]
Hi - Following removal Redmine functions as normal, no errors.
