### ISSUE TITLE
Redmine 5.0 (ruby 3.0) support

### ISSUE THREAD

**Issue by tomhub** [RealEnder/redmine_auditlog#5]
Seems like plugin needs update to work in redmine 5.0:

```
bundle exec rake db:migrate RAILS_ENV=production 
rake aborted!
LoadError: cannot load such file -- redmine_auditlog
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/usr/share/webapps/redmine/plugins/redmine_auditlog/init.rb:1:in `<top (required)>'
/usr/share/webapps/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/usr/share/webapps/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/usr/share/webapps/redmine/lib/redmine/plugin_loader.rb:108:in `each'
/usr/share/webapps/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:427:in `instance_exec'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:603:in `catch'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `each'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `invoke_before'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/reloader.rb:88:in `prepare!'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `instance_exec'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `run'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:60:in `run_initializers'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/application.rb:391:in `initialize!'
/usr/share/webapps/redmine/config/environment.rb:16:in `<top (required)>'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/application.rb:367:in `require_environment!'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `load'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:23:in `run'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:478:in `exec'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:31:in `dispatch'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:25:in `start'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/exe/bundle:49:in `block in <top (required)>'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/usr/share/webapps/redmine/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.31/exe/bundle:37:in `<top (required)>'
/usr/sbin/bundle:25:in `load'
/usr/sbin/bundle:25:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by san199332** [comment]
@tomhub 
Check out my fork https://github.com/san199332/redmine_auditlog this plugin version works with redmine 5.x
Tested on redmine version 5.0.3

**Comment by Kostas-Papapageorgiou** [comment]
> @tomhub Check out my fork https://github.com/san199332/redmine_auditlog this plugin version works with redmine 5.x Tested on redmine version 5.0.3

We installed @san199332 's fork in our redmine version 5.0.2 and it seems to work. 
Environment details:
```
  Redmine version                5.0.2.stable
  Ruby version                   2.7.2-p137 (2020-10-01) [x86_64-linux]
  Rails version                  6.1.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
```
